Repository DIT112-V19/group-01, pull requests merged in 2019-05, with the labels that each got.

#46 merge Arduino code and fix app
  BtSendData/app/src/main/java/com/example/myapplication/optionsPage.java
  merginArduino/src/obstacleAvoidanceWithSmartCar/obstacleAvoidanceWithSmartCar.ino
  mergingArduino/.gitignore
  mergingArduino/.travis.yml
  mergingArduino/include/README
  mergingArduino/lib/README
  mergingArduino/platformio.ini
  mergingArduino/src/mergingArduino/mergingArduino.ino
  mergingArduino/test/README
Labels: Sprint 5

#47 Styling the landing page of the app
  BtSendData/app/src/main/res/drawable/bgapp.png
  BtSendData/app/src/main/res/drawable/clover.png
  BtSendData/app/src/main/res/drawable/custom_button.xml
  BtSendData/app/src/main/res/layout/activity_welcome_page.xml
  BtSendData/app/src/main/res/values/styles.xml
Labels: Sprint 5

#50 manual control and alarm obstacle avoidance integrated
  BtManual/BtManual.ino
  BtSendData/app/src/main/java/com/example/myapplication/MainActivity.java
  BtSendData/app/src/main/java/com/example/myapplication/alarmPage.java
  BtSendData/app/src/main/java/com/example/myapplication/operatePage.java
  BtSendData/app/src/main/java/com/example/myapplication/optionsPage.java
  BtSendData/app/src/main/res/drawable-anydpi/returnbutton.xml
  BtSendData/app/src/main/res/drawable-hdpi/returnbutton.png
  BtSendData/app/src/main/res/drawable-mdpi/returnbutton.png
  BtSendData/app/src/main/res/drawable-xhdpi/returnbutton.png
  BtSendData/app/src/main/res/drawable-xxhdpi/returnbutton.png
  BtSendData/app/src/main/res/layout/activity_operate_page.xml
  merginArduino/src/obstacleAvoidanceWithSmartCar/obstacleAvoidanceWithSmartCar.ino
  mergingArduino/src/mergingArduino/mergingArduino.ino
  obstacleAvoidanceWIthSmartCar/.clang_complete
  obstacleAvoidanceWIthSmartCar/.gcc-flags.json
Labels: Sprint 5

#52 added return buttons
  BtSendData/app/src/main/java/com/example/myapplication/BluetoothConnectionService.java
  BtSendData/app/src/main/java/com/example/myapplication/MainActivity.java
  BtSendData/app/src/main/java/com/example/myapplication/alarmPage.java
  BtSendData/app/src/main/java/com/example/myapplication/optionsPage.java
  BtSendData/app/src/main/res/layout/activity_alarm_page.xml
  BtSendData/app/src/main/res/layout/activity_main.xml
  BtSendData/app/src/main/res/layout/activity_options_page.xml
Labels: Sprint 6

#51 styling the whole app layout
  BtSendData/app/src/main/res/drawable-anydpi/arrow_right.xml
  BtSendData/app/src/main/res/drawable-anydpi/arrows_left.xml
  BtSendData/app/src/main/res/drawable-anydpi/downward_arrow.xml
  BtSendData/app/src/main/res/drawable-anydpi/main_menu.xml
  BtSendData/app/src/main/res/drawable-anydpi/stopbutton.xml
  BtSendData/app/src/main/res/drawable-anydpi/upward_arrow.xml
  BtSendData/app/src/main/res/drawable/custom_button3.xml
  BtSendData/app/src/main/res/drawable/custom_edittext.xml
  BtSendData/app/src/main/res/layout/activity_alarm_page.xml
  BtSendData/app/src/main/res/layout/activity_main.xml
  BtSendData/app/src/main/res/layout/activity_operate_page.xml
  BtSendData/app/src/main/res/layout/activity_options_page.xml
  BtSendData/app/src/main/res/layout/device_adapter_view.xml
Labels: Sprint 6

#54 Set alarm
  BtSendData/app/src/main/java/com/example/myapplication/alarmPage.java
  BtSendData/app/src/main/res/layout/activity_alarm_page.xml
Labels: Sprint 5, Sprint 6

#53 Bug fix
  BtSendData/app/src/main/java/com/example/myapplication/MainActivity.java
  BtSendData/app/src/main/java/com/example/myapplication/alarmPage.java
  BtSendData/app/src/main/java/com/example/myapplication/operatePage.java
  BtSendData/app/src/main/java/com/example/myapplication/optionsPage.java
  BtSendData/app/src/main/res/layout/activity_alarm_page.xml
  BtSendData/app/src/main/res/layout/activity_main.xml
  BtSendData/app/src/main/res/layout/activity_options_page.xml
  BtSendData/app/src/main/res/layout/activity_welcome_page.xml
  BtSendData/app/src/main/res/values/strings.xml
Labels: Sprint 6

#55 Set alarm fix
  BtSendData/app/src/main/java/com/example/myapplication/alarmPage.java
  BtSendData/app/src/main/res/layout/activity_alarm_page.xml
Labels: Sprint 5, Sprint 6

#56 changed pins accordingly
  mergingArduino/src/mergingArduino/mergingArduino.ino
Labels: Sprint 5, Sprint 6

#57 Refactoring clean code back end sprint6
  mergingArduino/src/mergingArduino/mergingArduino.ino
Labels: Sprint 6

#58 Refactor
  BtSendData/app/src/main/java/com/example/myapplication/BluetoothConnectionService.java
  BtSendData/app/src/main/java/com/example/myapplication/DeviceListAdapter.java
  BtSendData/app/src/main/java/com/example/myapplication/MainActivity.java
  BtSendData/app/src/main/java/com/example/myapplication/WelcomePage.java
  BtSendData/app/src/main/java/com/example/myapplication/alarmPage.java
  BtSendData/app/src/main/java/com/example/myapplication/operatePage.java
  BtSendData/app/src/main/java/com/example/myapplication/optionsPage.java
Labels: Sprint 5

#60 Designing application
  BtSendData/app/src/main/res/drawable/background.png
  BtSendData/app/src/main/res/layout/activity_alarm_page.xml
  BtSendData/app/src/main/res/layout/activity_main.xml
  BtSendData/app/src/main/res/layout/activity_operate_page.xml
  BtSendData/app/src/main/res/layout/activity_options_page.xml
  BtSendData/app/src/main/res/layout/activity_welcome_page.xml
  BtSendData/app/src/main/res/layout/device_adapter_view.xml
  BtSendData/app/src/main/res/values/strings.xml
Labels: Sprint 6

#62 bugfix of listview
  BtSendData/app/src/main/java/com/example/myapplication/BluetoothConnectionService.java
  BtSendData/app/src/main/java/com/example/myapplication/DeviceListAdapter.java
  BtSendData/app/src/main/java/com/example/myapplication/MainActivity.java
  BtSendData/app/src/main/java/com/example/myapplication/alarmPage.java
  BtSendData/app/src/main/res/layout/activity_main.xml
  BtSendData/app/src/main/res/layout/device_adapter_view.xml
  BtSendData/app/src/main/res/values/colors.xml
Labels: Sprint 6, bug

#64 Adding basic buzzer code to mergingArduino
  mergingArduino/src/mergingArduino/mergingArduino.ino
Labels: Sprint 6

#65 Initial commit, integrate second ultrasonic sensor
  DoubleSensorTest/doubleSensorsTest.ino
Labels: Sprint 6

#66 fixed bug whileloop
  mergingArduino/src/mergingArduino/mergingArduino.ino
Labels: bug

#67 I fixed the arduino code
  mergingArduino/src/mergingArduino/mergingArduino.ino
Labels: bug

#69 Buzzer
  mergingArduino/src/mergingArduino/mergingArduino.ino
Labels: Sprint 6

#70 Cleaning app code
  BtSendData/app/src/main/AndroidManifest.xml
  BtSendData/app/src/main/java/com/example/myapplication/BluetoothConnectionService.java
  BtSendData/app/src/main/java/com/example/myapplication/OperateManually.java
  BtSendData/app/src/main/java/com/example/myapplication/SetAlarm.java
  BtSendData/app/src/main/java/com/example/myapplication/StartConnection.java
  BtSendData/app/src/main/java/com/example/myapplication/UserOptions.java
  BtSendData/app/src/main/java/com/example/myapplication/WelcomePage.java
  BtSendData/app/src/main/res/layout/activity_operate_manually.xml
  BtSendData/app/src/main/res/layout/activity_set_alarm.xml
  BtSendData/app/src/main/res/layout/activity_start_connection.xml
  BtSendData/app/src/main/res/layout/activity_user_options.xml
  BtSendData/app/src/main/res/layout/activity_welcome_page.xml
  BtSendData/app/src/main/res/layout/content_main.xml
  BtSendData/app/src/main/res/menu/menu_main.xml
  BtSendData/app/src/main/res/values/strings.xml
Labels: Sprint 6

#71 max 25 devices on arraylist
  BtSendData/app/src/main/java/com/example/myapplication/StartConnection.java
Labels: bug

#72 Improve avoidance
  mergingArduino/.gitignore
  mergingArduino/src/mergingArduino/.gitignore
  mergingArduino/src/mergingArduino/CppProperties.json
  mergingArduino/src/mergingArduino/mergingArduino.ino
Labels: Sprint 6

#73 refresh button added
  BtSendData/app/src/main/java/com/example/myapplication/StartConnection.java
  BtSendData/app/src/main/res/drawable-anydpi/refresh.xml
  BtSendData/app/src/main/res/drawable-hdpi/refresh.png
  BtSendData/app/src/main/res/drawable-mdpi/refresh.png
  BtSendData/app/src/main/res/drawable-xhdpi/refresh.png
  BtSendData/app/src/main/res/drawable-xxhdpi/refresh.png
  BtSendData/app/src/main/res/layout/activity_start_connection.xml
Labels: Sprint 6, bug

#74 added Documentation Folder and made Project-Proposal file
  Documentation/PROJECTPROPOSAL.md
Labels: Sprint 7

#75 Update README.md
  README.md
Labels: Sprint 7

#76 Update README.md
  README.md
Labels: Sprint 6

#77 Deleted the refresh button.
  BtSendData/app/src/main/java/com/example/myapplication/StartConnection.java
  BtSendData/app/src/main/res/layout/activity_start_connection.xml
Labels: Sprint 7

#78 Update README.md
  README.md
Labels: Sprint 7

#80 presentation upload
  Documentation/Speedy CarzalesV2.pdf
Labels: Sprint 7

#81 Deleted reundant files and lines of code
  BtManual/BtManual.ino
  DoubleSensorTest/doubleSensorsTest.ino
  basicObstacleAvoidance/basicObstacleAvoidance.ino
  improvedObstacleAvoidance/.vscode/ipch/7723843854f018ef/mmap_address.bin
  improvedObstacleAvoidance/improvedObstacleAvoidance.ino
  obstacleAvoidanceWIthSmartCar/.clang_complete
  obstacleAvoidanceWIthSmartCar/.gcc-flags.json
  obstacleAvoidanceWIthSmartCar/.gitignore
  obstacleAvoidanceWIthSmartCar/.pioenvs/do-not-modify-files-here.url
  obstacleAvoidanceWIthSmartCar/.pioenvs/structure.hash
  obstacleAvoidanceWIthSmartCar/.travis.yml
  obstacleAvoidanceWIthSmartCar/include/README
  obstacleAvoidanceWIthSmartCar/lib/README
  obstacleAvoidanceWIthSmartCar/platformio.ini
  obstacleAvoidanceWIthSmartCar/src/obstacleAvoidanceWithSmartCar/obstacleAvoidanceWithSmartCar.ino
  obstacleAvoidanceWIthSmartCar/test/README
Labels: Sprint 7

#82 Update README.md
  README.md
Labels: Sprint 6

#83 Update README.md
  README.md
Labels: Sprint 7
